accounts/urls.py
# accounts/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
]

djangobank/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

from accounts.views import MyView

from core.views import home, about

urlpatterns = [
    url('admin', admin.site.urls),
    url('login', MyView.login_view, name='login'),
    url('register', MyView.register_view, name='register'),
    url('logout', MyView.logout_view, name='logout'),

    url(r'^$', home, name='home'),


    url(r'^', include('transactions.urls', namespace='transactions')),
]


if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL,
        document_root=settings.STATIC_ROOT
        )
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
        )

transactions/urls.py
from django.conf.urls import url

from transactions.views import MyTransactions

urlpatterns = [

    url('deposit', MyTransactions.deposit_view, name='deposit'),
    url('withdrawal', MyTransactions.withdrawal_view, name='withdrawal'),
]

core/models.py
from django.db import models

# Create your models here.

core/views.py
from django.db.models import Sum
from django.shortcuts import render

from transactions.models import Deposit, Withdrawal


def home(request):
    if not request.user.is_authenticated:
        return render(request, "core/home.html", {})
    else:
        user = request.user
        deposit = Deposit.objects.filter(user=user)
        deposit_sum = deposit.aggregate(Sum('amount'))['amount__sum']
        withdrawal = Withdrawal.objects.filter(user=user)
        withdrawal_sum = withdrawal.aggregate(Sum('amount'))['amount__sum']

        context = {
                    "user": user,
                    "deposit": deposit,
                    "deposit_sum": deposit_sum,
                    "withdrawal": withdrawal,
                    "withdrawal_sum": withdrawal_sum,
                  }

        return render(request, "core/transactions.html", context)


def about(request):
    return render(request, "core/about.html", {})

core/templates/core/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}DjangoBank{% endblock title %}</title>

        <link rel="stylesheet" href='{% static "css/bootstrap.min.css" %}'>
        <link rel="stylesheet" href='{% static "css/bootstrap-theme.min.css" %}'>
  </head>

  <body>
    {% include "core/navbar.html" %}

    <div class="container-fluid" style="padding-top: 60px;">
        {% block content %}

        {% endblock content %}
    </div>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
        <script type="text/javascript" src="{% static 'js/jquery.min.js' %}" ></script>
        <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}" ></script>
  </body>
</html>

core/templates/core/home.html
{% extends 'core/base.html' %}

{% block title %} {{ block.super }}{% endblock title %}

{% block content %}
<div class="container" style="padding-top: 50px;">
    <div class="jumbotron text-center">
      <div class="container">
        <h2 class="jumbotron-heading">DjangoBank Private Unlimited</h2>
        <p class="lead text-muted">Welcome to the bank that never runs out of money</p>
        <p>Login with your account number or create an new account</p>
        <p>
          <a class="btn btn-primary btn-md" href="{% url 'login' %}" role="button">Login</a>
          <a class="btn btn-success btn-md" href="{% url 'register' %}" role="button">Create Account</a>
        </p>
      </div>
    </div>
</div>

{% endblock content %}

core/templates/core/messages.html
{% for message in messages %}
  <div class="alert {{ message.tags }} alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    {{ message }}
  </div>
{% endfor %}

core/templates/core/navbar.html
<nav class="navbar navbar-default navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'home' %}"  style="padding-left: 30px;">DjangoBank</a>

    </div>


    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="{% url 'transactions:deposit' %}">Deposit</a></li>
        <li><a href="{% url 'transactions:withdrawal' %}">Withdrawal</a></li>

      </ul>
      
      <ul class="nav navbar-nav navbar-right" style="padding-right: 30px;">
        {% if request.user.is_authenticated %}
        <li><a href="{% url 'logout' %}">Logout</a></li>
        {% else %}

         <li><a href="{% url 'login' %}"><span class="glyphicon glyphicon-log-in"></span>Log in</a></li>
        <li><a href="{% url 'register' %}"><span class="glyphicon glyphicon-user"></span>Create Account</a></li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>

core/templates/core/transactions.html
{% extends 'core/base.html' %}

{% block title %} Transactions | {{ block.super }}{% endblock title %}

{% block content %}
{% include "core/messages.html" %}

    <div class="page-header">
      <h1 class="text-center"><b>DjangoBank</b><br></h1>
      <center>
      <h2>Welcome to your Dashboard</h2>
        </center>
    </div>
    
<div class="row">

  <div class="col-xs-12 col-md-8 text-left">
    <h4><b>Account Name: </b>{{ user.full_name }}</h4>
    <h4><b>Location: </b>{{ user.city }}, {{ user.country }}</h4>
  </div>
  <div class="col-xs-6 col-md-4 text-left">
    <h4><b>Account Created: </b>{{ user.date_joined|date:'d-m-Y' }}</h4>
    <h4><b>Account No: </b>{{ user.account_no }}</h4><br><br>
    <div class="well">
    <h4 class="card"><b>Account Balance: </b>{{ user.balance }} ₹</h4>
    <a class="btn btn-success" href="{% url 'transactions:deposit' %}">Deposit</a>
    <a class="btn btn-danger" href="{% url 'transactions:withdrawal' %}">Withdrawal</a>
    </div>
  </div>

</div>




   
  </tbody>
</table>
<hr>

{% endblock content %}